from django.urls import path
from .views import (
    add_product,
    get_products,
    product_list,
    add_to_wishlist,
    get_wishlist,
    add_to_cart,
    get_cart,
    checkout,
    get_orders,
    create_payment_intent,
    create_checkout_session,
    update_cart_quantity,
    remove_from_cart,
    remove_from_wishlist,
    get_product_detail,
    product_detail,
    delete_product,
    place_order,
    artisan_orders,
    update_order_status,
    submit_review,
    get_reviews,
    artisan_by_email,
)


urlpatterns = [
    path("add-product/",                        add_product),
    path("products/",                           get_products),
    path("product-list/",                       product_list),
    path("add-to-wishlist/",                    add_to_wishlist),
    path("wishlist/<str:email>/",               get_wishlist),
    path("add-to-cart/",                        add_to_cart),
    path("cart/<str:email>/",                   get_cart),
    path("checkout/",                           checkout),
    path("orders/<str:email>/",                 get_orders),
    path("create-payment-intent/",              create_payment_intent),
    path("create-checkout-session/",            create_checkout_session),
    path("update-cart/",                        update_cart_quantity),
    path("remove-from-cart/",                   remove_from_cart),
    path("remove-from-wishlist/",               remove_from_wishlist),
    path("product-detail/<int:product_id>/",    get_product_detail),
    path("product/<int:id>/",                   product_detail,      name="product_detail"),
    path("delete-product/<int:product_id>/",    delete_product),
    path("place-order/",                        place_order),
    path("artisan-orders/",                     artisan_orders),
    path("update-order-status/<int:order_item_id>/", update_order_status),
    path("submit-review/",            submit_review),
    path("reviews/<int:artisan_id>/",  get_reviews),
    path("artisan-by-email/",          artisan_by_email),
   
    
]